In [1]:
import pandas as pd

In [53]:
df = pd.read_csv('external_data.csv')
df.head()

,numer_sta,date,pmer,tend,cod_tend,dd,ff,t,td,u,...,hnuage1,nnuage2,ctype2,hnuage2,nnuage3,ctype3,hnuage3,nnuage4,ctype4,hnuage4
0,7149,2021-01-01 00:00:00,100810,80,1,270,1.8,272.75,272.15,96,...,600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7149,2021-01-01 03:00:00,100920,110,3,300,1.7,271.25,270.95,98,...,1500.0,2.0,3.0,3000.0,NaN,NaN,NaN,NaN,NaN,NaN
2,7149,2021-01-01 06:00:00,100950,30,3,290,2.6,271.95,271.65,98,...,480.0,4.0,6.0,2000.0,6.0,3.0,3000.0,NaN,NaN,NaN
3,7149,2021-01-01 09:00:00,101100,150,2,280,1.7,272.45,272.05,97,...,1740.0,3.0,3.0,2800.0,NaN,NaN,NaN,NaN,NaN,NaN
4,7149,2021-01-01 12:00:00,101110,30,0,50,1.0,276.95,274.15,82,...,330.0,4.0,6.0,570.0,7.0,6.0,810.0,NaN,NaN,NaN

In [63]:
nouveaux_noms = {
    'numer_sta': 'Numéro de la station',
    'date': 'Date et heure',
    'pmer': 'Pression au niveau de la mer',
    'tend': 'Tendance de la pression',
    'cod_tend': 'Code de la tendance',
    'dd': 'Direction du vent',
    'ff': 'Vitesse du vent',
    't': 'Température de l\'air',
    'td': 'Point de rosée',
    'u': 'Humidité relative',
    'vv': 'Visibilité horizontale',
    'ww': 'État du temps',
    'w1': 'État du temps passé 1',
    'w2': 'État du temps passé 2',
    'n': 'Couverture nuageuse totale',
    'nbas': 'Hauteur de la base des nuages les plus bas',
    'hbas': 'Type de nuage le plus bas',
    'cl': 'Type de nuage bas',
    'cm': 'Type de nuage moyen',
    'ch': 'Type de nuage élevé',
    'pres': 'Pression atmosphérique',
    'niv_bar': 'Niveau barométrique',
    'geop': 'Hauteur géopotentielle',
    'tend24': 'Tendance de la pression sur 24 heures',
    'tn12': 'Température minimale sur 12 heures',
    'tn24': 'Température minimale sur 24 heures',
    'tx12': 'Température maximale sur 12 heures',
    'tx24': 'Température maximale sur 24 heures',
    'tminsol': 'Température minimale au sol',
    'sw': 'Radiation solaire',
    'tw': 'Température de l\'eau',
    'raf10': 'Rafale de vent sur 10 minutes',
    'rafper': 'Rafale de vent sur la période',
    'per': 'Période de la rafale de vent',
    'etat_sol': 'État du sol',
    'ht_neige': 'Hauteur de la neige',
    'ssfrai': 'Hauteur de la neige fraîche',
    'perssfrai': 'Période de la neige fraîche',
    'rr1': 'Précipitations sur 1 heure',
    'rr3': 'Précipitations sur 3 heures',
    'rr6': 'Précipitations sur 6 heures',
    'rr12': 'Précipitations sur 12 heures',
    'rr24': 'Précipitations sur 24 heures',
    'phenspe1': 'Phénomène spécial 1',
    'phenspe2': 'Phénomène spécial 2',
    'phenspe3': 'Phénomène spécial 3',
    'phenspe4': 'Phénomène spécial 4',
    'nnuage1': 'Type de nuage 1',
    'ctype1': 'Type de nuage 1 (code)',
    'hnuage1': 'Hauteur de la base du nuage 1',
    'nnuage2': 'Type de nuage 2',
    'ctype2': 'Type de nuage 2 (code)',
    'hnuage2': 'Hauteur de la base du nuage 2',
    'nnuage3': 'Type de nuage 3',
    'ctype3': 'Type de nuage 3 (code)',
    'hnuage3': 'Hauteur de la base du nuage 3',
    'nnuage4': 'Type de nuage 4',
    'ctype4': 'Type de nuage 4 (code)',
    'hnuage4': 'Hauteur de la base du nuage 4'
}

# Renommer les colonnes
df.rename(columns=nouveaux_noms, inplace=True)

# Afficher les premières lignes du DataFrame pour vérifier les changements
df.head()

,Date et heure,Température de l'air,Humidité relative,Visibilité horizontale,Vitesse du vent,Rafale de vent sur 10 minutes,Précipitations sur 3 heures,Précipitations sur 1 heure
0,2021-01-01 00:00:00,272.75,96,990,1.8,2.5,0.0,0.0
1,2021-01-01 03:00:00,271.25,98,210,1.7,2.2,0.0,0.0
2,2021-01-01 06:00:00,271.95,98,3660,2.6,3.2,0.0,0.0
3,2021-01-01 09:00:00,272.45,97,3500,1.7,2.3,0.2,0.0
4,2021-01-01 12:00:00,276.95,82,8000,1.0,2.5,0.0,0.0

In [64]:
colonnes_a_conserver = [
    'Date et heure', 'Température de l\'air', 'Humidité relative',
    'Visibilité horizontale', 'Vitesse du vent', 'Rafale de vent sur 10 minutes',
    'Précipitations sur 3 heures', 'Précipitations sur 1 heure'
]

df = df[colonnes_a_conserver]
df['Date et heure'] = pd.to_datetime(df['Date et heure'])

df.head()

,Date et heure,Température de l'air,Humidité relative,Visibilité horizontale,Vitesse du vent,Rafale de vent sur 10 minutes,Précipitations sur 3 heures,Précipitations sur 1 heure
0,2021-01-01 00:00:00,272.75,96,990,1.8,2.5,0.0,0.0
1,2021-01-01 03:00:00,271.25,98,210,1.7,2.2,0.0,0.0
2,2021-01-01 06:00:00,271.95,98,3660,2.6,3.2,0.0,0.0
3,2021-01-01 09:00:00,272.45,97,3500,1.7,2.3,0.2,0.0
4,2021-01-01 12:00:00,276.95,82,8000,1.0,2.5,0.0,0.0

On a un relevé météorologique toutes les 3 heures alors que notre dataset a un relevé toutes les heures. Il faut donc combler le gap.

In [65]:
# Créer un DataFrame avec des intervalles horaires
date_min = df['Date et heure'].min()
date_max = df['Date et heure'].max()
date_range = pd.date_range(start=date_min, end=date_max, freq='h')
df_hourly = pd.DataFrame(date_range, columns=['Date et heure'])

# Fusionner les données horaires avec les données originales
df_hourly = df_hourly.merge(df, on='Date et heure', how='left')

df_hourly.head()

,Date et heure,Température de l'air,Humidité relative,Visibilité horizontale,Vitesse du vent,Rafale de vent sur 10 minutes,Précipitations sur 3 heures,Précipitations sur 1 heure
0,2020-09-01 00:00:00,285.75,81.0,30000.0,1.6,2.4,0.0,0.0
1,2020-09-01 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-09-01 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-09-01 03:00:00,283.95,88.0,25000.0,1.1,1.5,0.0,0.0
4,2020-09-01 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Calculer les précipitations moyennes sur les 2 heures précédentes
df_hourly['Précipitations sur 2 heures'] = (df_hourly['Précipitations sur 3 heures'] - df_hourly['Précipitations sur 1 heure']) / 2

df_hourly = df_hourly[df_hourly['Précipitations horaires'] != 0.0]

df_hourly.head()

,Date et heure,Température de l'air,Humidité relative,Visibilité horizontale,Vitesse du vent,Rafale de vent sur 10 minutes,Précipitations sur 3 heures,Précipitations sur 1 heure,Précipitations sur 2 heures
0,2020-09-01 00:00:00,285.75,81.0,30000.0,1.6,2.4,0.0,0.0,0.0
1,2020-09-01 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-09-01 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-09-01 03:00:00,283.95,88.0,25000.0,1.1,1.5,0.0,0.0,0.0
4,2020-09-01 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
# Interpoler les précipitations pour chaque heure
df_hourly['Précipitations sur 1 heure'] = df_hourly['Précipitations sur 1 heure'].ffill()
df_hourly['Précipitations sur 2 heures'] = df_hourly['Précipitations sur 2 heures'].ffill()

df_hourly.head()

,Date et heure,Température de l'air,Humidité relative,Visibilité horizontale,Vitesse du vent,Rafale de vent sur 10 minutes,Précipitations sur 3 heures,Précipitations sur 1 heure,Précipitations sur 2 heures
0,2020-09-01 00:00:00,285.75,81.0,30000.0,1.6,2.4,0.0,0.0,0.0
1,2020-09-01 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
2,2020-09-01 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
3,2020-09-01 03:00:00,283.95,88.0,25000.0,1.1,1.5,0.0,0.0,0.0
4,2020-09-01 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0

In [49]:
# Calculer les précipitations pour chaque heure
df_hourly['Précipitations horaires'] = df_hourly['Précipitations sur 1 heure']

# Remplir les valeurs manquantes pour les autres colonnes
for col in colonnes_a_conserver[1:]:
    df_hourly[col] = df_hourly[col].ffill()

df_hourly.head()

,Date et heure,Température de l'air,Humidité relative,Visibilité horizontale,Vitesse du vent,Rafale de vent sur 10 minutes,Précipitations sur 3 heures,Précipitations sur 1 heure,Précipitations sur 2 heures,Précipitations horaires
0,2020-09-01 00:00:00,285.75,81.0,30000.0,1.6,2.4,0.0,0.0,0.0,0.0
1,2020-09-01 01:00:00,285.75,81.0,30000.0,1.6,2.4,0.0,0.0,0.0,0.0
2,2020-09-01 02:00:00,285.75,81.0,30000.0,1.6,2.4,0.0,0.0,0.0,0.0
3,2020-09-01 03:00:00,283.95,88.0,25000.0,1.1,1.5,0.0,0.0,0.0,0.0
4,2020-09-01 04:00:00,283.95,88.0,25000.0,1.1,1.5,0.0,0.0,0.0,0.0

In [52]:
df_hourly = df_hourly[df_hourly['Précipitations horaires'] != 0.0]

df_hourly.head(15)

,Date et heure,Température de l'air,Humidité relative,Visibilité horizontale,Vitesse du vent,Rafale de vent sur 10 minutes,Précipitations sur 3 heures,Précipitations sur 1 heure,Précipitations sur 2 heures,Précipitations horaires
102,2020-09-05 06:00:00,288.95,81.0,40960.0,2.8,4.4,-0.1,-0.1,0.0,-0.1
103,2020-09-05 07:00:00,288.95,81.0,40960.0,2.8,4.4,-0.1,-0.1,0.0,-0.1
104,2020-09-05 08:00:00,288.95,81.0,40960.0,2.8,4.4,-0.1,-0.1,0.0,-0.1
450,2020-09-19 18:00:00,293.95,84.0,1720.0,4.2,7.9,1.4,1.4,0.0,1.4
451,2020-09-19 19:00:00,293.95,84.0,1720.0,4.2,7.9,1.4,1.4,0.0,1.4
452,2020-09-19 20:00:00,293.95,84.0,1720.0,4.2,7.9,1.4,1.4,0.0,1.4
462,2020-09-20 06:00:00,290.25,90.0,20000.0,1.1,1.6,0.2,0.2,0.0,0.2
463,2020-09-20 07:00:00,290.25,90.0,20000.0,1.1,1.6,0.2,0.2,0.0,0.2
464,2020-09-20 08:00:00,290.25,90.0,20000.0,1.1,1.6,0.2,0.2,0.0,0.2
546,2020-09-23 18:00:00,290.15,89.0,6000.0,5.9,8.7,5.0,2.4,1.3,2.4
547,2020-09-23 19:00:00,290.15,89.0,6000.0,5.9,8.7,5.0,2.4,1.3,2.4
548,2020-09-23 20:00:00,290.15,89.0,6000.0,5.9,8.7,5.0,2.4,1.3,2.4
549,2020-09-23 21:00:00,289.65,94.0,6480.0,4.6,8.7,1.0,0.8,0.1,0.8
550,2020-09-23 22:00:00,289.65,94.0,6480.0,4.6,8.7,1.0,0.8,0.1,0.8
551,2020-09-23 23:00:00,289.65,94.0,6480.0,4.6,8.7,1.0,0.8,0.1,0.8