In [51]:
# we import the necessary modules
import pandas as pd
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt

In [52]:
# first we import the data
data = pd.read_parquet(Path("data") / "train.parquet")

In [53]:
# let's visualize the first few rows of the dataset
data.head()

,counter_id,counter_name,site_id,site_name,bike_count,date,counter_installation_date,coordinates,counter_technical_id,latitude,longitude,log_bike_count
48321,100007049-102007049,28 boulevard Diderot E-O,100007049,28 boulevard Diderot,0.0,2020-09-01 02:00:00,2013-01-18,"48.846028,2.375429",Y2H15027244,48.846028,2.375429,0.000000
48324,100007049-102007049,28 boulevard Diderot E-O,100007049,28 boulevard Diderot,1.0,2020-09-01 03:00:00,2013-01-18,"48.846028,2.375429",Y2H15027244,48.846028,2.375429,0.693147
48327,100007049-102007049,28 boulevard Diderot E-O,100007049,28 boulevard Diderot,0.0,2020-09-01 04:00:00,2013-01-18,"48.846028,2.375429",Y2H15027244,48.846028,2.375429,0.000000
48330,100007049-102007049,28 boulevard Diderot E-O,100007049,28 boulevard Diderot,4.0,2020-09-01 15:00:00,2013-01-18,"48.846028,2.375429",Y2H15027244,48.846028,2.375429,1.609438
48333,100007049-102007049,28 boulevard Diderot E-O,100007049,28 boulevard Diderot,9.0,2020-09-01 18:00:00,2013-01-18,"48.846028,2.375429",Y2H15027244,48.846028,2.375429,2.302585

In [54]:
# let's visualize somme main information about the dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 496827 entries, 48321 to 929187
Data columns (total 12 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   counter_id                 496827 non-null  category
 1   counter_name               496827 non-null  category
 2   site_id                    496827 non-null  int64
 3   site_name                  496827 non-null  category
 4   bike_count                 496827 non-null  float64
 5   date                       496827 non-null  datetime64[ns]
 6   counter_installation_date  496827 non-null  datetime64[ns]
 7   coordinates                496827 non-null  category
 8   counter_technical_id       496827 non-null  category
 9   latitude                   496827 non-null  float64
 10  longitude                  496827 non-null  float64
 11  log_bike_count             496827 non-null  float64
dtypes: category(5), datetime64[ns](2), float64(4), int64(1)
memory usage: 32.7 MB

In [55]:
# let's see if there are any missing values in the data
missing_values_count = data.isnull().any(axis=1).sum()
print(f"Number of lines with missing values: {missing_values_count}")

Number of lines with missing values: 0

In [ ]:
def _encode_dates(X):
    X = X.copy()
    X["year"] = X["date"].dt.year
    X["month"] = X["date"].dt.month
    X["day"] = X["date"].dt.day
    X["weekday"] = X["date"].dt.weekday
    X["hour"] = X["date"].dt.hour
    return X

# let's separate the year, the month, the day of the month, the day of the week and the hour
data = _encode_dates(data)
min_date = data['date'].min().strftime('%Y-%m-%d')
max_date = data['date'].max().strftime('%Y-%m-%d')
data.head()

,counter_id,counter_name,site_id,site_name,bike_count,date,counter_installation_date,coordinates,counter_technical_id,latitude,longitude,log_bike_count,year,month,day,weekday,hour,just_date
48321,100007049-102007049,28 boulevard Diderot E-O,100007049,28 boulevard Diderot,0.0,2020-09-01 02:00:00,2013-01-18,"48.846028,2.375429",Y2H15027244,48.846028,2.375429,0.000000,2020,9,1,1,2,2020-09-01
48324,100007049-102007049,28 boulevard Diderot E-O,100007049,28 boulevard Diderot,1.0,2020-09-01 03:00:00,2013-01-18,"48.846028,2.375429",Y2H15027244,48.846028,2.375429,0.693147,2020,9,1,1,3,2020-09-01
48327,100007049-102007049,28 boulevard Diderot E-O,100007049,28 boulevard Diderot,0.0,2020-09-01 04:00:00,2013-01-18,"48.846028,2.375429",Y2H15027244,48.846028,2.375429,0.000000,2020,9,1,1,4,2020-09-01
48330,100007049-102007049,28 boulevard Diderot E-O,100007049,28 boulevard Diderot,4.0,2020-09-01 15:00:00,2013-01-18,"48.846028,2.375429",Y2H15027244,48.846028,2.375429,1.609438,2020,9,1,1,15,2020-09-01
48333,100007049-102007049,28 boulevard Diderot E-O,100007049,28 boulevard Diderot,9.0,2020-09-01 18:00:00,2013-01-18,"48.846028,2.375429",Y2H15027244,48.846028,2.375429,2.302585,2020,9,1,1,18,2020-09-01

In [57]:
import holidays
vacances = holidays.CountryHoliday('France', years=[2020, 2021])
vacances_dates = pd.to_datetime(list(vacances.keys())).date

# let's add information about if a given day is durong a holidays or during the weekend
data["IsHolidays"] = data["just_date"].isin(vacances_dates).astype(int)
data['IsWeekend'] = data['weekday'].apply(lambda x: 1 if x >= 5 else 0)

In [58]:
# let's look at how the data changed
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 496827 entries, 48321 to 929187
Data columns (total 20 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   counter_id                 496827 non-null  category
 1   counter_name               496827 non-null  category
 2   site_id                    496827 non-null  int64
 3   site_name                  496827 non-null  category
 4   bike_count                 496827 non-null  float64
 5   date                       496827 non-null  datetime64[ns]
 6   counter_installation_date  496827 non-null  datetime64[ns]
 7   coordinates                496827 non-null  category
 8   counter_technical_id       496827 non-null  category
 9   latitude                   496827 non-null  float64
 10  longitude                  496827 non-null  float64
 11  log_bike_count             496827 non-null  float64
 12  year                       496827 non-null  int64
 13  month                      496827 non-null  int64
 14  day                        496827 non-null  int64
 15  weekday                    496827 non-null  int64
 16  hour                       496827 non-null  int64
 17  just_date                  496827 non-null  datetime64[ns]
 18  IsHolidays                 496827 non-null  int64
 19  IsWeekend                  496827 non-null  int64
dtypes: category(5), datetime64[ns](3), float64(4), int64(8)
memory usage: 63.0 MB

In [59]:
# let's get rid of some useless data
new_data = data.drop(columns=["just_date", "day", "counter_name", "site_name", "bike_count", "date", "counter_installation_date", "coordinates", "counter_technical_id", "latitude", "longitude"])
new_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 496827 entries, 48321 to 929187
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   counter_id      496827 non-null  category
 1   site_id         496827 non-null  int64
 2   log_bike_count  496827 non-null  float64
 3   year            496827 non-null  int64
 4   month           496827 non-null  int64
 5   weekday         496827 non-null  int64
 6   hour            496827 non-null  int64
 7   IsHolidays      496827 non-null  int64
 8   IsWeekend       496827 non-null  int64
dtypes: category(1), float64(1), int64(7)
memory usage: 34.6 MB

In [60]:
weather_data = pd.read_csv(Path("data") / "external_data.csv")
weather_data = weather_data.filter(items=['numer_sta', 'date', 'pmer', 'pres', 'dd', 'ff', 'ww', 't', 'u', 'vv', 'n'])
weather_data.head()
weather_data

,numer_sta,date,pmer,pres,dd,ff,ww,t,u,vv,n
0,7149,2021-01-01 00:00:00,100810,99680,270,1.8,2,272.75,96,990,10.0
1,7149,2021-01-01 03:00:00,100920,99790,300,1.7,40,271.25,98,210,25.0
2,7149,2021-01-01 06:00:00,100950,99820,290,2.6,3,271.95,98,3660,90.0
3,7149,2021-01-01 09:00:00,101100,99970,280,1.7,10,272.45,97,3500,50.0
4,7149,2021-01-01 12:00:00,101110,100000,50,1.0,2,276.95,82,8000,90.0
...,...,...,...,...,...,...,...,...,...,...,...
3317,7149,2020-09-30 09:00:00,101540,100480,230,4.4,3,289.95,82,18000,90.0
3318,7149,2020-09-30 12:00:00,101320,100270,190,4.9,1,292.05,66,25000,90.0
3319,7149,2020-09-30 15:00:00,101140,100090,190,4.1,1,291.55,72,25000,90.0
3320,7149,2020-09-30 18:00:00,101020,99960,190,2.7,3,290.15,73,40820,100.0
3321,7149,2020-09-30 21:00:00,100880,99820,170,2.4,2,288.35,85,25250,90.0

In [61]:
numerical_columns = ['year', 'month', 'weekday', 'hour', 'IsHolidays', 'IsWeekend']
categorical_columns = ['counter_id', 'site_id']

# Preprocessing
from sklearn.preprocessing import MinMaxScaler, LabelEncoder

# Preprocess numerical features (scaling)
scaler = MinMaxScaler()
new_data[numerical_columns] = scaler.fit_transform(new_data[numerical_columns])

# Preprocess categorical features (encoding)
le = LabelEncoder()
new_data[categorical_columns] = new_data[categorical_columns].apply(le.fit_transform)

In [ ]:
X = new_data.drop('log_bike_count', axis=1)
y = new_data['log_bike_count']

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor

models = {
    "Linear Regression": LinearRegression(),
    "Random Forest": RandomForestRegressor(n_estimators=100, random_state=42),
    "Gradient Boosting": GradientBoostingRegressor(n_estimators=100, random_state=42),
    "K-Nearest Neighbors": KNeighborsRegressor(),
    #"Support Vector Regression": SVR(),
    #"Decision Tree": DecisionTreeRegressor(random_state=42)
}

results = {}
print(X, y)

        counter_id  site_id  year     month   weekday      hour  IsHolidays  \
48321            1        0   0.0  0.727273  0.166667  0.086957         0.0
48324            1        0   0.0  0.727273  0.166667  0.130435         0.0
48327            1        0   0.0  0.727273  0.166667  0.173913         0.0
48330            1        0   0.0  0.727273  0.166667  0.652174         0.0
48333            1        0   0.0  0.727273  0.166667  0.782609         0.0
...            ...      ...   ...       ...       ...       ...         ...
929175          54       29   1.0  0.727273  0.500000  0.260870         0.0
929178          54       29   1.0  0.727273  0.500000  0.434783         0.0
929181          54       29   1.0  0.727273  0.500000  0.652174         0.0
929184          54       29   1.0  0.727273  0.500000  0.956522         0.0
929187          54       29   1.0  0.727273  0.500000  1.000000         0.0

        IsWeekend
48321         0.0
48324         0.0
48327         0.0
48330         0.0
48333         0.0
...           ...
929175        0.0
929178        0.0
929181        0.0
929184        0.0
929187        0.0

[496827 rows x 8 columns] 48321     0.000000
48324     0.693147
48327     0.000000
48330     1.609438
48333     2.302585
            ...
929175    6.100319
929178    4.983607
929181    5.389072
929184    3.091042
929187    2.772589
Name: log_bike_count, Length: 496827, dtype: float64

In [63]:
for model_name, model in models.items():
    # Perform cross-validation and calculate the mean and standard deviation of the score
    cv_scores = cross_val_score(model, X, y, cv=5, scoring='neg_mean_squared_error', n_jobs=-1)  # Using MSE as the evaluation metric
    
    # Compute the average of the cross-validation scores
    mean_mse = np.mean(cv_scores)
    mean_rmse = np.sqrt(-mean_mse)  # Convert MSE to RMSE
    
    # Store the results
    results[model_name] = {
        "Mean RMSE": mean_rmse,
    }

KeyboardInterrupt:

In [ ]:
import pandas as pd
results_df = pd.DataFrame(results).T
print(results_df)

                     Mean RMSE
Linear Regression     1.578319
Random Forest         1.154580
Gradient Boosting     1.071951
K-Nearest Neighbors   1.161246

On nva regarder les significations des données de external_data.

In [ ]:
dict_external_data = {
    'pmer' : 'pression atmosphérique au niveau de la mer',
    'dd' : 'direction du vent',
    'ff' : 'vitesse du vent',
    't' : 'température en Kelvin',
    'u' : 'humidité relative',
    'numer_sta' : 'numéro de la station',
    'date' : 'date',
    'vv' : 'visibilité en km',
    'ww' : 'puissance du vent',
    'n' : 'cloud coverage',
    'pres' : 'pression atmosphérique',
}