In [40]:
import pandas as pd

In [41]:
df = pd.read_csv("mouvements-sociaux-depuis-2002.csv", sep=";")
df.head()

,Date,date_de_fin,Motif exprimé,Organisations syndicales,Métiers ciblés par le préavis,Population devant travailler ciblee par le préavis,Nombre de grévistes du préavis,Taux de grévistes au sein de la population concernée par le préavis
0,2002-03-13,2002-03-15,Journée de manifestation et d'action contre la...,"CGT,SUD Rail,CFDT,FO","conducteur,agent de manoeuvre,chef de bord,acc...",28760.0,1491.0,5.2
1,2003-02-10,2003-02-12,Journée d'action des agents du Matériel : moye...,"CGT,CFDT,CFTC","agent de manoeuvre,logistique,ingénierie et ma...",3935.0,694.0,17.6
2,2003-05-22,2003-05-22,Revendications suite au discussions sur le règ...,SUD Rail,"conducteur,agent de manoeuvre,chef de bord,acc...",126896.0,8.0,0.0
3,2003-05-25,NaN,Retraites.,"CGT,SUD Rail,CFDT,FO","conducteur,agent de manoeuvre,chef de bord,acc...",557.0,23.0,4.1
4,2004-05-12,2004-05-14,Politique de l'emploi (besoins service public ...,"CGT,SUD Rail,CFDT,FO","conducteur,agent de manoeuvre,chef de bord,acc...",137739.0,30472.0,22.1

In [42]:
# Convertir la colonne 'Date' en type datetime
df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values(by='Date')

# Sélectionner les lignes où la colonne 'Date' est à partir de 2020
df = df[df['Date'] >= '2020-01-01']

df.head()

,Date,date_de_fin,Motif exprimé,Organisations syndicales,Métiers ciblés par le préavis,Population devant travailler ciblee par le préavis,Nombre de grévistes du préavis,Taux de grévistes au sein de la population concernée par le préavis
447,2020-01-01,NaN,Réforme des retraites,"CGT,SUD Rail,CFDT,FO,UNSA",NaN,NaN,NaN,16.8
255,2020-01-02,NaN,Réforme des retraites,"CGT,SUD Rail,CFDT,FO,UNSA",NaN,NaN,NaN,6.9
349,2020-01-03,NaN,Réforme des retraites,"CGT,SUD Rail,CFDT,FO,UNSA",NaN,NaN,NaN,6.2
448,2020-01-04,NaN,Réforme des retraites,"CGT,SUD Rail,CFDT,FO,UNSA",NaN,NaN,NaN,12.6
173,2020-01-05,NaN,Réforme des retraites,"CGT,SUD Rail,CFDT,FO,UNSA",NaN,NaN,NaN,12.6

In [43]:
print(df.isna().sum())

Date                                                                    0
date_de_fin                                                            85
Motif exprimé                                                           0
Organisations syndicales                                                0
Métiers ciblés par le préavis                                          85
Population devant travailler ciblee par le préavis                     85
Nombre de grévistes du préavis                                         85
Taux de grévistes au sein de la population concernée par le préavis     0
dtype: int64

On va conserver uniquement les manifestations qui ont des syndicats communs à la RATP et la SNCF

In [44]:
# Liste des syndicats à vérifier
syndicats = ['CGT', 'CFDT', 'SUD-Rail', 'UNSA', 'FO']

# Fonction pour vérifier si au moins un syndicat est présent dans la liste
def contains_syndicat(row, syndicats):
    return any(syndicat in row for syndicat in syndicats)

# Appliquer la fonction à la colonne 'Organisations'
df_filtered = df[df['Organisations syndicales'].apply(contains_syndicat, syndicats=syndicats)]

df_filtered.head()

,Date,date_de_fin,Motif exprimé,Organisations syndicales,Métiers ciblés par le préavis,Population devant travailler ciblee par le préavis,Nombre de grévistes du préavis,Taux de grévistes au sein de la population concernée par le préavis
447,2020-01-01,NaN,Réforme des retraites,"CGT,SUD Rail,CFDT,FO,UNSA",NaN,NaN,NaN,16.8
255,2020-01-02,NaN,Réforme des retraites,"CGT,SUD Rail,CFDT,FO,UNSA",NaN,NaN,NaN,6.9
349,2020-01-03,NaN,Réforme des retraites,"CGT,SUD Rail,CFDT,FO,UNSA",NaN,NaN,NaN,6.2
448,2020-01-04,NaN,Réforme des retraites,"CGT,SUD Rail,CFDT,FO,UNSA",NaN,NaN,NaN,12.6
173,2020-01-05,NaN,Réforme des retraites,"CGT,SUD Rail,CFDT,FO,UNSA",NaN,NaN,NaN,12.6

Je conserve uniquement l'info du taux de gréviste journalier car seul porteur d'information

In [45]:
df_filtered = df_filtered[['Date', 'Taux de grévistes au sein de la population concernée par le préavis']]
df_filtered = df_filtered.rename(columns={'Taux de grévistes au sein de la population concernée par le préavis': 'striker_ratio'})
df_filtered = df_filtered.rename(columns={'Date': 'date'})

In [ ]:
df_filtered.head()

          date  striker_ratio
447 2020-01-01           16.8
255 2020-01-02            6.9
349 2020-01-03            6.2
448 2020-01-04           12.6
173 2020-01-05           12.6

In [47]:
hours = pd.DataFrame({'hour': range(24)})

# Fusionner les heures avec le DataFrame d'origine
df_filtered['key'] = 1
hours['key'] = 1
df_full = pd.merge(df_filtered, hours, on='key').drop('key', axis=1)
df_full['striker_ratio'] = df_full.groupby('date')['striker_ratio'].ffill()

df_full['date'] = pd.to_datetime(df_full['date'].astype(str) + ' ' + df_full['hour'].astype(str) + ':00:00')
df_full.drop(columns='hour')

                    date  striker_ratio
0    2020-01-01 00:00:00           16.8
1    2020-01-01 01:00:00           16.8
2    2020-01-01 02:00:00           16.8
3    2020-01-01 03:00:00           16.8
4    2020-01-01 04:00:00           16.8
...                  ...            ...
2011 2024-03-08 19:00:00            2.6
2012 2024-03-08 20:00:00            2.6
2013 2024-03-08 21:00:00            2.6
2014 2024-03-08 22:00:00            2.6
2015 2024-03-08 23:00:00            2.6

[2016 rows x 2 columns]

In [ ]:
df_full.head()

                  date  striker_ratio  hour
0  2020-01-01 00:00:00           16.8     0
1  2020-01-01 01:00:00           16.8     1
2  2020-01-01 02:00:00           16.8     2
3  2020-01-01 03:00:00           16.8     3
4  2020-01-01 04:00:00           16.8     4
5  2020-01-01 05:00:00           16.8     5
6  2020-01-01 06:00:00           16.8     6
7  2020-01-01 07:00:00           16.8     7
8  2020-01-01 08:00:00           16.8     8
9  2020-01-01 09:00:00           16.8     9
10 2020-01-01 10:00:00           16.8    10
11 2020-01-01 11:00:00           16.8    11
12 2020-01-01 12:00:00           16.8    12
13 2020-01-01 13:00:00           16.8    13
14 2020-01-01 14:00:00           16.8    14
15 2020-01-01 15:00:00           16.8    15
16 2020-01-01 16:00:00           16.8    16
17 2020-01-01 17:00:00           16.8    17
18 2020-01-01 18:00:00           16.8    18
19 2020-01-01 19:00:00           16.8    19
20 2020-01-01 20:00:00           16.8    20
21 2020-01-01 21:00:00           16.8    21
22 2020-01-01 22:00:00           16.8    22
23 2020-01-01 23:00:00           16.8    23
24 2020-01-02 00:00:00            6.9     0
25 2020-01-02 01:00:00            6.9     1
26 2020-01-02 02:00:00            6.9     2
27 2020-01-02 03:00:00            6.9     3
28 2020-01-02 04:00:00            6.9     4
29 2020-01-02 05:00:00            6.9     5
30 2020-01-02 06:00:00            6.9     6
31 2020-01-02 07:00:00            6.9     7
32 2020-01-02 08:00:00            6.9     8
33 2020-01-02 09:00:00            6.9     9
34 2020-01-02 10:00:00            6.9    10
35 2020-01-02 11:00:00            6.9    11
36 2020-01-02 12:00:00            6.9    12
37 2020-01-02 13:00:00            6.9    13
38 2020-01-02 14:00:00            6.9    14
39 2020-01-02 15:00:00            6.9    15

In [49]:
df_filtered.to_csv("Propre_taux_grévistes_SNCF.csv", index=False)